### ISSUE TITLE
cs4414 is over, can we make this public?

### ISSUE THREAD

**Issue by nathantypanski** [lenary/cs4414-ps4#23]
I like the work that we did here, and think that we did a good job. It would be nice to have the repo public.

@lenary thoughts?

**Comment by lenary** [comment]
I'm happy with it, though I should probably drop a licence in there
somewhere.

On Sun, May 25, 2014 at 3:32 PM, Nathan Typanski
notifications@github.comwrote:

> I like the work that we did here, and think that we did a good job. It
> would be nice to have the repo public.
> 
> @lenary https://github.com/lenary thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lenary/cs4414-ps4/issues/23
> .

## 

Samuel Elliott
sam@lenary.co.uk
http://lenary.co.uk/
+44 (0)7891 993 664

**Comment by lenary** [comment]
done
